ALTER TABLE restaurants 
ADD COLUMN IF NOT EXISTS is_instagram_enabled BOOLEAN DEFAULT TRUE,
ADD COLUMN IF NOT EXISTS is_tiktok_enabled BOOLEAN DEFAULT TRUE,
ADD COLUMN IF NOT EXISTS is_website_enabled BOOLEAN DEFAULT TRUE,
ADD COLUMN IF NOT EXISTS is_google_review_enabled BOOLEAN DEFAULT TRUE;
